; Faind 内嵌 Everything 配置
; 启动参数: Everything64.exe -startup -config Everything.ini
[Everything]
run_in_background=1
check_for_updates_on_startup=0
allow_multiple_instances=0
run_as_admin=0
; 持久化数据库 —— 第二次启动秒级加载，无需重新扫描 MFT
db_location=Everything.db

